services:
  app:
    depends_on:
      - postgres
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: develop
      # Use the following to test performance
      # target: test
    volumes:
      - .:/opt/blackledger
    ports:
      - "8000:8000"
    environment:
      DEBUG: "True"
      AUTH_DISABLED: "True"
      AUTH_JWKS_URL: http://keycloak:8001/realms/blackledger/protocol/openid-connect/certs
      AUTH_ISS: http://localhost:8001/realms/blackledger
      DATABASE_NAME: blackledger_test
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_URL: postgresql://postgres:password@postgres:5432/blackledger_test
      DATABASE_DIALECT: psycopg

  migrate:
    depends_on:
      - postgres
      - app
    image: blackledger-app
    entrypoint: ["script/migrate.sh"]
    volumes:
      - .:/opt/blackledger
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/blackledger
      DATABASE_DIALECT: psycopg

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: blackledger
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - .:/opt/blackledger

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    depends_on:
      - postgres
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: password
      KC_HTTP_PORT: "8001"
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
    command: ["start-dev"]
    ports:
      - "8001:8001"
    restart: on-failure

volumes:
  pgdata:
