version: "3.7"
services:
  blackledger:
    depends_on:
      - postgres
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: develop
    # # Use the following to test performance
    # command: ["gunicorn", "-w", "16", "-k", "uvicorn.workers.UvicornWorker",
    #     "--bind", "0.0.0.0:8000", "blackledger.http:app"]
    volumes:
      - .:/opt/blackledger
    ports:
      - "8000:8000"
    environment:
      DEBUG: "True"
      DATABASE_NAME: blackledger
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_URL: postgresql://postgres:password@postgres:5432/blackledger
      DATABASE_DIALECT: psycopg

  migrate:
    depends_on:
      - postgres
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: deploy
    entrypoint: ["script/migrate.sh"]
    volumes:
      - .:/opt/blackledger
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/blackledger
      DATABASE_DIALECT: psycopg

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: blackledger
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - .:/opt/blackledger

volumes:
  pgdata:
