use sqlx::{PgPool, Row, QueryBuilder, Postgres};

use crate::error::{ApiError, ApiResult};
use crate::models::account::{
    Account, AccountBalance, CreateAccount, NormalBalance, UpdateAccount,
};

pub async fn create_account(pool: &PgPool, input: &CreateAccount) -> ApiResult<Account> {
    // ID will be generated by database bigid() function
    let normal_str = match input.normal {
        NormalBalance::Debit => "DR",
        NormalBalance::Credit => "CR",
    };

    let record = sqlx::query!(
        r#"
        INSERT INTO account (ledger_id, parent_id, name, number, normal)
        VALUES ($1, $2, $3, $4, $5)
        RETURNING id, ledger_id, parent_id, name, number, normal, version, created
        "#,
        input.ledger_id,
        input.parent_id,
        input.name,
        input.number,
        normal_str
    )
    .fetch_one(pool)
    .await?;

    Ok(Account {
        id: record.id,
        ledger_id: record.ledger_id,
        parent_id: record.parent_id,
        name: record.name,
        number: record.number,
        normal: match record.normal.as_str() {
            "DR" => NormalBalance::Debit,
            "CR" => NormalBalance::Credit,
            _ => NormalBalance::Debit,
        },
        version: record.version,
        created: record.created,
    })
}

pub async fn get_account_by_id(pool: &PgPool, id: i64) -> ApiResult<Account> {
    let record = sqlx::query!(
        r#"SELECT id, ledger_id, parent_id, name, number, normal, version, created FROM account WHERE id = $1"#,
        id
    )
    .fetch_one(pool)
    .await
    .map_err(|e| match e {
        sqlx::Error::RowNotFound => ApiError::NotFound(format!("Account {} not found", id)),
        _ => ApiError::Database(e),
    })?;

    Ok(Account {
        id: record.id,
        ledger_id: record.ledger_id,
        parent_id: record.parent_id,
        name: record.name,
        number: record.number,
        normal: match record.normal.as_str() {
            "DR" => NormalBalance::Debit,
            "CR" => NormalBalance::Credit,
            _ => NormalBalance::Debit,
        },
        version: record.version,
        created: record.created,
    })
}

pub async fn update_account(pool: &PgPool, id: i64, input: &UpdateAccount) -> ApiResult<Account> {
    let record = sqlx::query!(
        r#"
        UPDATE account
        SET name = COALESCE($2, name)
        WHERE id = $1
        RETURNING id, ledger_id, parent_id, name, number, normal, version, created
        "#,
        id,
        input.name.as_deref()
    )
    .fetch_one(pool)
    .await
    .map_err(|e| match e {
        sqlx::Error::RowNotFound => ApiError::NotFound(format!("Account {} not found", id)),
        _ => ApiError::Database(e),
    })?;

    Ok(Account {
        id: record.id,
        ledger_id: record.ledger_id,
        parent_id: record.parent_id,
        name: record.name,
        number: record.number,
        normal: match record.normal.as_str() {
            "DR" => NormalBalance::Debit,
            "CR" => NormalBalance::Credit,
            _ => NormalBalance::Debit,
        },
        version: record.version,
        created: record.created,
    })
}

pub async fn list_accounts(
    pool: &PgPool,
    ledger_id: Option<i64>,
    parent_id: Option<i64>,
    limit: Option<i64>,
    offset: Option<i64>,
) -> ApiResult<Vec<Account>> {
    // Due to SQLx limitations with dynamic queries, we'll use a simpler approach
    let accounts = if ledger_id.is_some() && parent_id.is_some() {
        sqlx::query_as::<_, Account>(
            r#"
            SELECT * FROM account
            WHERE ledger_id = $1 AND parent_id = $2
            ORDER BY number
            LIMIT $3 OFFSET $4
            "#,
        )
        .bind(ledger_id.unwrap())
        .bind(parent_id.unwrap())
        .bind(limit.unwrap_or(100))
        .bind(offset.unwrap_or(0))
        .fetch_all(pool)
        .await?
    } else if ledger_id.is_some() {
        sqlx::query_as::<_, Account>(
            r#"
            SELECT * FROM account
            WHERE ledger_id = $1
            ORDER BY number
            LIMIT $2 OFFSET $3
            "#,
        )
        .bind(ledger_id.unwrap())
        .bind(limit.unwrap_or(100))
        .bind(offset.unwrap_or(0))
        .fetch_all(pool)
        .await?
    } else if parent_id.is_some() {
        sqlx::query_as::<_, Account>(
            r#"
            SELECT * FROM account
            WHERE parent_id = $1
            ORDER BY number
            LIMIT $2 OFFSET $3
            "#,
        )
        .bind(parent_id.unwrap())
        .bind(limit.unwrap_or(100))
        .bind(offset.unwrap_or(0))
        .fetch_all(pool)
        .await?
    } else {
        sqlx::query_as::<_, Account>(
            r#"
            SELECT * FROM account
            ORDER BY number
            LIMIT $1 OFFSET $2
            "#,
        )
        .bind(limit.unwrap_or(100))
        .bind(offset.unwrap_or(0))
        .fetch_all(pool)
        .await?
    };

    Ok(accounts)
}

pub async fn get_account_balances(
    pool: &PgPool,
    ledger_id: i64,
    account_ids: Option<Vec<i64>>,
) -> ApiResult<Vec<AccountBalance>> {
    let balances = if let Some(ids) = account_ids {
        sqlx::query(
            r#"
            SELECT 
                e.account_id,
                e.currency_code,
                SUM(COALESCE(e.dr, 0) - COALESCE(e.cr, 0)) as balance
            FROM entry e
            INNER JOIN transaction t ON e.transaction_id = t.id
            WHERE t.ledger_id = $1 AND e.account_id = ANY($2)
            GROUP BY e.account_id, e.currency_code
            "#,
        )
        .bind(ledger_id)
        .bind(&ids)
        .map(|row: sqlx::postgres::PgRow| AccountBalance {
            account_id: row.get("account_id"),
            currency_code: row.get("currency_code"),
            balance: row.get("balance"),
        })
        .fetch_all(pool)
        .await?
    } else {
        sqlx::query(
            r#"
            SELECT 
                e.account_id,
                e.currency_code,
                SUM(COALESCE(e.dr, 0) - COALESCE(e.cr, 0)) as balance
            FROM entry e
            INNER JOIN transaction t ON e.transaction_id = t.id
            WHERE t.ledger_id = $1
            GROUP BY e.account_id, e.currency_code
            "#,
        )
        .bind(ledger_id)
        .map(|row: sqlx::postgres::PgRow| AccountBalance {
            account_id: row.get("account_id"),
            currency_code: row.get("currency_code"),
            balance: row.get("balance"),
        })
        .fetch_all(pool)
        .await?
    };

    Ok(balances)
}

pub async fn search_accounts(
    pool: &PgPool,
    params: &crate::api::search::AccountSearchParams,
) -> ApiResult<Vec<Account>> {
    let limit = params.base.get_limit() as i64;
    let offset = params.base.get_offset() as i64;

    // Use QueryBuilder for dynamic SQL generation
    let mut query_builder: QueryBuilder<Postgres> = QueryBuilder::new(
        "SELECT id, ledger_id, parent_id, name, number, normal, version, created FROM account WHERE 1=1"
    );

    // Handle comma-delimited list of IDs
    if let Some(ref id_list) = params.id {
        let ids: Vec<i64> = id_list
            .split(',')
            .filter_map(|s| s.trim().parse::<i64>().ok())
            .collect();
        if !ids.is_empty() {
            query_builder.push(" AND id IN (");
            let mut separated = query_builder.separated(", ");
            for id in ids {
                separated.push_bind(id);
            }
            query_builder.push(")");
        }
    }

    // Handle comma-delimited list of ledger IDs  
    if let Some(ref ledger_id_list) = params.ledger_id {
        let ledger_ids: Vec<i64> = ledger_id_list
            .split(',')
            .filter_map(|s| s.trim().parse::<i64>().ok())
            .collect();
        if !ledger_ids.is_empty() {
            query_builder.push(" AND ledger_id IN (");
            let mut separated = query_builder.separated(", ");
            for ledger_id in ledger_ids {
                separated.push_bind(ledger_id);
            }
            query_builder.push(")");
        }
    }

    // Handle comma-delimited list of parent IDs
    if let Some(ref parent_id_list) = params.parent_id {
        let parent_ids: Vec<i64> = parent_id_list
            .split(',')
            .filter_map(|s| s.trim().parse::<i64>().ok())
            .collect();
        if !parent_ids.is_empty() {
            query_builder.push(" AND parent_id IN (");
            let mut separated = query_builder.separated(", ");
            for parent_id in parent_ids {
                separated.push_bind(parent_id);
            }
            query_builder.push(")");
        }
    }

    // Handle comma-delimited list of version IDs
    if let Some(ref version_list) = params.version {
        let versions: Vec<i64> = version_list
            .split(',')
            .filter_map(|s| s.trim().parse::<i64>().ok())
            .collect();
        if !versions.is_empty() {
            query_builder.push(" AND version IN (");
            let mut separated = query_builder.separated(", ");
            for version in versions {
                separated.push_bind(version);
            }
            query_builder.push(")");
        }
    }

    // Handle comma-delimited list of account numbers
    if let Some(ref number_list) = params.number {
        let numbers: Vec<i16> = number_list
            .split(',')
            .filter_map(|s| s.trim().parse::<i16>().ok())
            .collect();
        if !numbers.is_empty() {
            query_builder.push(" AND number IN (");
            let mut separated = query_builder.separated(", ");
            for number in numbers {
                separated.push_bind(number);
            }
            query_builder.push(")");
        }
    }

    // Handle comma-delimited list of name patterns (regex patterns)
    if let Some(ref name_patterns) = params.name {
        let patterns: Vec<&str> = name_patterns.split(',').map(|s| s.trim()).collect();
        if !patterns.is_empty() {
            query_builder.push(" AND (");
            let mut first = true;
            for pattern in patterns {
                if !first {
                    query_builder.push(" OR ");
                }
                query_builder.push("name ~* ");
                query_builder.push_bind(pattern);
                first = false;
            }
            query_builder.push(")");
        }
    }

    // Handle normal balance type (DR/CR, case-insensitive, also accepts debit/credit)
    if let Some(ref normal) = params.normal {
        let normal_upper = normal.to_uppercase();
        let normal_value = match normal_upper.as_str() {
            "DR" | "DEBIT" => Some("DR"),
            "CR" | "CREDIT" => Some("CR"),
            _ => None,
        };
        
        if let Some(normal_val) = normal_value {
            query_builder.push(" AND normal = ");
            query_builder.push_bind(normal_val);
        }
    }

    // Add sorting based on SearchParams with whitelist validation
    const ALLOWED_COLUMNS: &[&str] = &["id", "ledger_id", "parent_id", "name", "number", "created", "normal", "version"];
    if let Some(order_clause) = params.base.parse_order_by(ALLOWED_COLUMNS) {
        query_builder.push(" ORDER BY ");
        query_builder.push(order_clause);
    } else {
        // Default ordering
        query_builder.push(" ORDER BY created DESC");
    }

    // Add pagination
    query_builder.push(" LIMIT ");
    query_builder.push_bind(limit);
    query_builder.push(" OFFSET ");
    query_builder.push_bind(offset);

    // Execute the query
    let query = query_builder.build();
    let rows = query.fetch_all(pool).await?;

    let mut accounts = Vec::new();
    for row in rows {
        let account = Account {
            id: row.try_get("id")?,
            ledger_id: row.try_get("ledger_id")?,
            parent_id: row.try_get("parent_id")?,
            name: row.try_get("name")?,
            number: row.try_get("number")?,
            normal: match row.try_get::<String, _>("normal")?.as_str() {
                "DR" => NormalBalance::Debit,
                "CR" => NormalBalance::Credit,
                _ => NormalBalance::Debit,
            },
            version: row.try_get("version")?,
            created: row.try_get("created")?,
        };
        accounts.push(account);
    }

    Ok(accounts)
}

pub async fn count_accounts(
    pool: &PgPool,
    params: &crate::api::search::AccountSearchParams,
) -> ApiResult<i64> {
    // Use QueryBuilder for dynamic SQL generation
    let mut query_builder: QueryBuilder<Postgres> = QueryBuilder::new(
        "SELECT COUNT(*) as count FROM account WHERE 1=1"
    );

    // Handle comma-delimited list of IDs
    if let Some(ref id_list) = params.id {
        let ids: Vec<i64> = id_list
            .split(',')
            .filter_map(|s| s.trim().parse::<i64>().ok())
            .collect();
        if !ids.is_empty() {
            query_builder.push(" AND id IN (");
            let mut separated = query_builder.separated(", ");
            for id in ids {
                separated.push_bind(id);
            }
            query_builder.push(")");
        }
    }

    // Handle comma-delimited list of ledger IDs  
    if let Some(ref ledger_id_list) = params.ledger_id {
        let ledger_ids: Vec<i64> = ledger_id_list
            .split(',')
            .filter_map(|s| s.trim().parse::<i64>().ok())
            .collect();
        if !ledger_ids.is_empty() {
            query_builder.push(" AND ledger_id IN (");
            let mut separated = query_builder.separated(", ");
            for ledger_id in ledger_ids {
                separated.push_bind(ledger_id);
            }
            query_builder.push(")");
        }
    }

    // Handle comma-delimited list of parent IDs
    if let Some(ref parent_id_list) = params.parent_id {
        let parent_ids: Vec<i64> = parent_id_list
            .split(',')
            .filter_map(|s| s.trim().parse::<i64>().ok())
            .collect();
        if !parent_ids.is_empty() {
            query_builder.push(" AND parent_id IN (");
            let mut separated = query_builder.separated(", ");
            for parent_id in parent_ids {
                separated.push_bind(parent_id);
            }
            query_builder.push(")");
        }
    }

    // Handle comma-delimited list of version IDs
    if let Some(ref version_list) = params.version {
        let versions: Vec<i64> = version_list
            .split(',')
            .filter_map(|s| s.trim().parse::<i64>().ok())
            .collect();
        if !versions.is_empty() {
            query_builder.push(" AND version IN (");
            let mut separated = query_builder.separated(", ");
            for version in versions {
                separated.push_bind(version);
            }
            query_builder.push(")");
        }
    }

    // Handle comma-delimited list of account numbers
    if let Some(ref number_list) = params.number {
        let numbers: Vec<i16> = number_list
            .split(',')
            .filter_map(|s| s.trim().parse::<i16>().ok())
            .collect();
        if !numbers.is_empty() {
            query_builder.push(" AND number IN (");
            let mut separated = query_builder.separated(", ");
            for number in numbers {
                separated.push_bind(number);
            }
            query_builder.push(")");
        }
    }

    // Handle comma-delimited list of name patterns (regex patterns)
    if let Some(ref name_patterns) = params.name {
        let patterns: Vec<&str> = name_patterns.split(',').map(|s| s.trim()).collect();
        if !patterns.is_empty() {
            query_builder.push(" AND (");
            let mut first = true;
            for pattern in patterns {
                if !first {
                    query_builder.push(" OR ");
                }
                query_builder.push("name ~* ");
                query_builder.push_bind(pattern);
                first = false;
            }
            query_builder.push(")");
        }
    }

    // Handle normal balance type (DR/CR, case-insensitive, also accepts debit/credit)
    if let Some(ref normal) = params.normal {
        let normal_upper = normal.to_uppercase();
        let normal_value = match normal_upper.as_str() {
            "DR" | "DEBIT" => Some("DR"),
            "CR" | "CREDIT" => Some("CR"),
            _ => None,
        };
        
        if let Some(normal_val) = normal_value {
            query_builder.push(" AND normal = ");
            query_builder.push_bind(normal_val);
        }
    }

    // Execute the query
    let query = query_builder.build();
    let row = query.fetch_one(pool).await?;
    let count: i64 = row.try_get("count")?;

    Ok(count)
}
