use sqlx::{PgPool, Row};

use crate::error::{ApiError, ApiResult};
use crate::models::account::{
    Account, AccountBalance, CreateAccount, NormalBalance, UpdateAccount,
};

pub async fn create_account(pool: &PgPool, input: &CreateAccount) -> ApiResult<Account> {
    // ID will be generated by database bigid() function
    let normal_str = match input.normal {
        NormalBalance::Debit => "DR",
        NormalBalance::Credit => "CR",
    };

    let record = sqlx::query!(
        r#"
        INSERT INTO account (ledger_id, parent_id, name, number, normal)
        VALUES ($1, $2, $3, $4, $5)
        RETURNING id, ledger_id, parent_id, name, number, normal, version, created
        "#,
        input.ledger_id,
        input.parent_id,
        input.name,
        input.number,
        normal_str
    )
    .fetch_one(pool)
    .await?;

    Ok(Account {
        id: record.id,
        ledger_id: record.ledger_id,
        parent_id: record.parent_id,
        name: record.name,
        number: record.number,
        normal: match record.normal.as_str() {
            "DR" => NormalBalance::Debit,
            "CR" => NormalBalance::Credit,
            _ => NormalBalance::Debit,
        },
        version: record.version,
        created: record.created,
    })
}

pub async fn get_account_by_id(pool: &PgPool, id: i64) -> ApiResult<Account> {
    let record = sqlx::query!(
        r#"SELECT id, ledger_id, parent_id, name, number, normal, version, created FROM account WHERE id = $1"#,
        id
    )
    .fetch_one(pool)
    .await
    .map_err(|e| match e {
        sqlx::Error::RowNotFound => ApiError::NotFound(format!("Account {} not found", id)),
        _ => ApiError::Database(e),
    })?;

    Ok(Account {
        id: record.id,
        ledger_id: record.ledger_id,
        parent_id: record.parent_id,
        name: record.name,
        number: record.number,
        normal: match record.normal.as_str() {
            "DR" => NormalBalance::Debit,
            "CR" => NormalBalance::Credit,
            _ => NormalBalance::Debit,
        },
        version: record.version,
        created: record.created,
    })
}

pub async fn update_account(pool: &PgPool, id: i64, input: &UpdateAccount) -> ApiResult<Account> {
    let record = sqlx::query!(
        r#"
        UPDATE account
        SET name = COALESCE($2, name)
        WHERE id = $1
        RETURNING id, ledger_id, parent_id, name, number, normal, version, created
        "#,
        id,
        input.name.as_deref()
    )
    .fetch_one(pool)
    .await
    .map_err(|e| match e {
        sqlx::Error::RowNotFound => ApiError::NotFound(format!("Account {} not found", id)),
        _ => ApiError::Database(e),
    })?;

    Ok(Account {
        id: record.id,
        ledger_id: record.ledger_id,
        parent_id: record.parent_id,
        name: record.name,
        number: record.number,
        normal: match record.normal.as_str() {
            "DR" => NormalBalance::Debit,
            "CR" => NormalBalance::Credit,
            _ => NormalBalance::Debit,
        },
        version: record.version,
        created: record.created,
    })
}

pub async fn list_accounts(
    pool: &PgPool,
    ledger_id: Option<i64>,
    parent_id: Option<i64>,
    limit: Option<i64>,
    offset: Option<i64>,
) -> ApiResult<Vec<Account>> {
    // Due to SQLx limitations with dynamic queries, we'll use a simpler approach
    let accounts = if ledger_id.is_some() && parent_id.is_some() {
        sqlx::query_as::<_, Account>(
            r#"
            SELECT * FROM account
            WHERE ledger_id = $1 AND parent_id = $2
            ORDER BY number
            LIMIT $3 OFFSET $4
            "#,
        )
        .bind(ledger_id.unwrap())
        .bind(parent_id.unwrap())
        .bind(limit.unwrap_or(100))
        .bind(offset.unwrap_or(0))
        .fetch_all(pool)
        .await?
    } else if ledger_id.is_some() {
        sqlx::query_as::<_, Account>(
            r#"
            SELECT * FROM account
            WHERE ledger_id = $1
            ORDER BY number
            LIMIT $2 OFFSET $3
            "#,
        )
        .bind(ledger_id.unwrap())
        .bind(limit.unwrap_or(100))
        .bind(offset.unwrap_or(0))
        .fetch_all(pool)
        .await?
    } else if parent_id.is_some() {
        sqlx::query_as::<_, Account>(
            r#"
            SELECT * FROM account
            WHERE parent_id = $1
            ORDER BY number
            LIMIT $2 OFFSET $3
            "#,
        )
        .bind(parent_id.unwrap())
        .bind(limit.unwrap_or(100))
        .bind(offset.unwrap_or(0))
        .fetch_all(pool)
        .await?
    } else {
        sqlx::query_as::<_, Account>(
            r#"
            SELECT * FROM account
            ORDER BY number
            LIMIT $1 OFFSET $2
            "#,
        )
        .bind(limit.unwrap_or(100))
        .bind(offset.unwrap_or(0))
        .fetch_all(pool)
        .await?
    };

    Ok(accounts)
}

pub async fn get_account_balances(
    pool: &PgPool,
    ledger_id: i64,
    account_ids: Option<Vec<i64>>,
) -> ApiResult<Vec<AccountBalance>> {
    let balances = if let Some(ids) = account_ids {
        sqlx::query(
            r#"
            SELECT 
                e.account_id,
                e.currency_code,
                SUM(COALESCE(e.dr, 0) - COALESCE(e.cr, 0)) as balance
            FROM entry e
            INNER JOIN transaction t ON e.transaction_id = t.id
            WHERE t.ledger_id = $1 AND e.account_id = ANY($2)
            GROUP BY e.account_id, e.currency_code
            "#,
        )
        .bind(ledger_id)
        .bind(&ids)
        .map(|row: sqlx::postgres::PgRow| AccountBalance {
            account_id: row.get("account_id"),
            currency_code: row.get("currency_code"),
            balance: row.get("balance"),
        })
        .fetch_all(pool)
        .await?
    } else {
        sqlx::query(
            r#"
            SELECT 
                e.account_id,
                e.currency_code,
                SUM(COALESCE(e.dr, 0) - COALESCE(e.cr, 0)) as balance
            FROM entry e
            INNER JOIN transaction t ON e.transaction_id = t.id
            WHERE t.ledger_id = $1
            GROUP BY e.account_id, e.currency_code
            "#,
        )
        .bind(ledger_id)
        .map(|row: sqlx::postgres::PgRow| AccountBalance {
            account_id: row.get("account_id"),
            currency_code: row.get("currency_code"),
            balance: row.get("balance"),
        })
        .fetch_all(pool)
        .await?
    };

    Ok(balances)
}

pub async fn search_accounts(
    pool: &PgPool,
    params: &crate::api::search::AccountSearchParams,
) -> ApiResult<Vec<Account>> {
    let limit = params.base.get_limit() as i64;
    let offset = params.base.get_offset() as i64;

    // Build dynamic query based on search parameters
    let mut query = String::from("SELECT * FROM account WHERE 1=1");
    let mut bindings = vec![];
    let mut bind_count = 0;

    if let Some(ledger_id) = params.ledger_id {
        bind_count += 1;
        query.push_str(&format!(" AND ledger_id = ${}", bind_count));
        bindings.push(ledger_id.to_string());
    }

    if let Some(parent_id) = params.parent_id {
        bind_count += 1;
        query.push_str(&format!(" AND parent_id = ${}", bind_count));
        bindings.push(parent_id.to_string());
    }

    if let Some(ref name) = params.name {
        bind_count += 1;
        query.push_str(&format!(" AND name ILIKE ${}", bind_count));
        bindings.push(format!("%{}%", name));
    }

    if let Some(ref number) = params.number {
        bind_count += 1;
        query.push_str(&format!(" AND number::text LIKE ${}", bind_count));
        bindings.push(format!("%{}%", number));
    }

    // Add sorting based on SearchParams
    if let Some(order_clause) = params.base.parse_order_by() {
        query.push_str(&format!(" ORDER BY {}", order_clause));
    } else {
        // Default ordering
        query.push_str(" ORDER BY created DESC");
    }

    // Add pagination
    bind_count += 1;
    query.push_str(&format!(" LIMIT ${}", bind_count));
    bindings.push(limit.to_string());

    bind_count += 1;
    query.push_str(&format!(" OFFSET ${}", bind_count));
    bindings.push(offset.to_string());

    // For simplicity, we'll use the existing list_accounts function with filters
    // In a production system, you'd build a dynamic query
    let accounts = if let Some(ledger_id) = params.ledger_id {
        list_accounts(
            pool,
            Some(ledger_id),
            params.parent_id,
            Some(limit),
            Some(offset),
        )
        .await?
    } else {
        list_accounts(pool, None, params.parent_id, Some(limit), Some(offset)).await?
    };

    Ok(accounts)
}

pub async fn count_accounts(
    pool: &PgPool,
    params: &crate::api::search::AccountSearchParams,
) -> ApiResult<i64> {
    let mut query = String::from("SELECT COUNT(*) FROM account WHERE 1=1");

    if let Some(ledger_id) = params.ledger_id {
        query.push_str(&format!(" AND ledger_id = {}", ledger_id));
    }

    if let Some(parent_id) = params.parent_id {
        query.push_str(&format!(" AND parent_id = {}", parent_id));
    }

    if let Some(ref name) = params.name {
        query.push_str(&format!(" AND name ILIKE '%{}%'", name));
    }

    // For simplicity, using a basic count
    let count: (i64,) = if let Some(ledger_id) = params.ledger_id {
        sqlx::query_as("SELECT COUNT(*) FROM account WHERE ledger_id = $1")
            .bind(ledger_id)
            .fetch_one(pool)
            .await?
    } else {
        sqlx::query_as("SELECT COUNT(*) FROM account")
            .fetch_one(pool)
            .await?
    };

    Ok(count.0)
}
